inherit_gem:
  rubocop-shopify: rubocop.yml

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/StringLiterals:
  EnforcedStyle: single_quotes

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

plugins:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
