language: ruby
rvm:
  - 2.5.1
services:
  - postgresql
before_install:
  - sudo /etc/init.d/postgresql stop
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key
    add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main
    9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get install postgresql-11.2
  - sudo /etc/init.d/postgresql start
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.dist config/secrets.yml
  - gem install bundler
before_script:
  - sudo service postgresql restart
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle install
  - bundle exec rake db:drop
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rspec ./spec/requests
