sudo: false
language: ruby
rvm:
  - 2.5.1
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
services:
  - postgresql
before_install:
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.dist config/secrets.yml
  - gem install bundler
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle install
  - bundle exec rake db:drop
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rspec ./spec/requests
