sudo: false
language: ruby
rvm:
  - 2.5.1
addons:
  postgresql: "11.2"
services:
  - postgresql
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11 
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.dist config/secrets.yml
  - gem install bundler
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
script:
  - bundle install
  - bundle exec rake db:drop
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rspec ./spec/requests
