language: ruby
rvm:
  - 2.6.3

services:
  - postgresql
  - mysql

before_install:
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.dist config/secrets.yml
  - gem install bundler

env:
  - DB=mysql
  - DB=postgres

before_script:
  - sudo service postgresql restart
  - psql -c 'create database otb_test;' -U postgres
  - mysql -e 'create database otb_test'

script:
  - bundle install
  - bundle exec rake db:drop
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rspec ./spec/requests
