language: ruby
rvm:
  - 2.6.3
services:
  - postgresql
before_install:
  - sudo apt-get -y install postgresql postgresql-contrib libpq-dev
  - sudo /etc/init.d/postgresql start
  - sudo -u postgres createuser -s postgres
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.dist config/secrets.yml
  - gem install bundler
before_script:
  - sudo service postgresql restart
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle install
  - bundle exec rake db:drop
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rspec ./spec/requests
