default: &default
  adapter: <%= ENV['DB_ADAPTER'] || 'postgresql' %>
  encoding: utf8
  pool: 50
  schema_search_path: "public,shared_extensions"
  username: <%= ENV['DB_USERNAME'] || 'user'%>
  host: <%= ENV['DB_HOSTNAME'] || 'localhost' %>
  schema_search_path: public, postgis
  password: <%= ENV['DB_PASSWORD' || 'password'] %>
  database: <%= ENV['DB_NAME'] || 'otb' %>

mysql: &mysql
  <<: *default
  adapter: mysql2
  database: public
  username: <%= Rails.application.credentials.dig(:dbTest, :mysql, :user) %>
  password: <%= Rails.application.credentials.dig(:dbTest, :mysql, :pw) %>
  host: <%= Rails.application.credentials.dig(:dbTest, :mysql, :host) %>


development:
  <<: *default
  database: <%= Rails.application.credentials.dig(:dbDev, :db) %>
  username: <%= Rails.application.credentials.dig(:dbDev, :user) %>
  password: <%= Rails.application.credentials.dig(:dbDev, :pw) %>
  host: <%= Rails.application.credentials.dig(:dbDev, :host) %>

staging:
  <<: *default
  database: <%= Rails.application.credentials.dig(:rdsStaging, :db) %>
  username: <%= Rails.application.credentials.dig(:rdsStaging, :user) %>
  password: <%= Rails.application.credentials.dig(:rdsStaging, :pw) %>
  host: <%= Rails.application.credentials.dig(:rdsStaging, :host) %>

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:rdsProduction, :db) %>
  username: <%= Rails.application.credentials.dig(:rdsProduction, :user) %>
  password: <%= Rails.application.credentials.dig(:rdsProduction, :pw) %>
  host: <%= Rails.application.credentials.dig(:rdsProduction, :host) %>

test:
  <<: *default
  database: <%= ENV['TEST_DB_NAME'] || 'otb_test' %>
